# Generated by Django 3.2.6 on 2021-08-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='text',
            field=models.TextField(),
        ),
    ]
